### ISSUE TITLE
Issue with reversed inside of buffered polygon

### ISSUE THREAD

**Issue by sheerun** [rowanwins/geojson-buffer#2]
Video is better than thousand words so:

https://v.usetapes.com/bGpWXNFdY4

Do you have some ideas how to handle this case? Simple overlap check won't work because resulting polygon doesn't have any intersection. It is just mirror image of original interior

**Comment by rowanwins** [comment]
Hi @sheerun 

I suspect this case may be resolved by updating the dependency of `polygon-clipping`...

**Comment by sheerun** [comment]
I think this was because your algorithm didn't work, not because polygon-clipping is wrong. Anyway I'm sending another PR with potential solution..
