### ISSUE TITLE
Should I union features?

### ISSUE THREAD

**Issue by sheerun** [rowanwins/geojson-buffer#3]
I'm trying to create full implementation for this, and I have a question: it seems that current buffer implementation of turf doesn't join different shapes within feature collection when they overlap each other, as so: https://imgur.com/a/Zbb325i

Should I preserve this behavior? I think more reasonable option is to rather return single MultiPolygon that is a union of all features within this

**Comment by rowanwins** [comment]
Hi @sheerun

Mmm i think each feature or geometry in should return an equivalent out. If people want to union the output that should be up to them. For example if you had properties on a feature you'd want to able to retain them. Make sense?

**Comment by sheerun** [comment]
👍
