### ISSUE TITLE
Deploy to netlify

### ISSUE THREAD

**Issue by sheerun** [rowanwins/geojson-buffer#5]
Hello,

I encourage you to deploy demo to netlify instead of keeping "dist" and "docs" directories inside repository. They contain duplicated (bundled) code

**Comment by rowanwins** [comment]
Hi @sheerun

I think that's just some dodgy webpack config on my part, I'll take a look at it when i review your other contributions

**Comment by rowanwins** [comment]
Resolved by [this commit](https://github.com/rowanwins/geojson-buffer/commit/cf1c24e95c8269b6d0295a43db7a33456063828f) although I'm not using netlify, as suggested above I just fixed the webpack config.
